### ISSUE TITLE
BUILDS_PATH folder resolution fails sometimes

### ISSUE THREAD

**Issue by vadim0x60** [vadim0x60/auto-als#2]

**Comment by braj11** [comment]
BUILDS path folder set Path.cwd()/UnityBuilds. Tested it on my system where the issue was recurring. Path (__name__) was referring to the file from which the auto-als was imported/called. Path.cwd() always refers to current working directory of the envs file, where the Unity Builds folder is located

**Comment by braj11** [comment]
Earlier fix had some issues. Issue fully fixed with Path(__file__).parent.parent.resolve() refers to the envs.py itself
